//@ USER LOGIN
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

//@ USER REGISTER
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

//@ UPDATE PROFILE
export const USER_UPDATE_LIKES_REQUEST = "USER_UPDATE_LIKES_REQUEST";
export const USER_UPDATE_LIKES_SUCCESS = "USER_UPDATE_LIKES_SUCCESS";
export const USER_UPDATE_LIKES_FAIL = "USER_UPDATE_LIKES_FAIL";
export const USER_UPDATE_LIKES_RESET = "USER_UPDATE_LIKES_RESET";